---
title: "Regresión Lineal Multivariada"
subtitle: 'Taller de Investigación: Política Cuantitativa "CUANTIPOL" - UNMSM'
date: "2022-03-25"
author1: "Joel Hu \n **[@luccemhu](https://github.com/luccemhu)** \n a20196510@pucp.edu.pe"
author2: "Gianfranco Romero" 
output:
  rmdformats::downcute:
    downcute_theme: "chaos"
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: github
    code_folding: "hide"
    includes:
      in_header: header-hu.html
      in_footer: header-hu.html
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(rio)
organization = 'https://github.com/Estadistica-AnalisisPolitico'
repo = '/DataFiles-estadistica/raw/main/'
file = 'hsb_ok.xlsx'
hsb = import(paste0(organization, repo, file)) # importando 3 datas

#str(hsb)
```

```{r}
# FORMATEAMOS:
categoricals = c("SEX", "RACE", "SES", "SCTYP", "HSP", "CAR")

hsb[, categoricals] = lapply(hsb[, categoricals], as.factor)

# nominales
hsb$SEX = factor(hsb$SEX,
                 levels = c(1, 2),
                 labels = c("Male", "Female"))

hsb$RACE = factor(
  hsb$RACE,
  levels = c(1, 2, 3, 4),
  labels = c("Hispanic", "Asian", "Black", "White")
)

hsb$HSP = factor(
  hsb$HSP,
  levels = c(1, 2, 3),
  labels = c("General", "Academic", "Vocational")
)

hsb$SCTYP = factor(hsb$SCTYP,
                   levels = c(1, 2),
                   labels = c("Public", "Private"))

# a ordinal:
hsb$SES = ordered(hsb$SES,
                  levels = c(1, 2, 3),
                  labels = c("Low", "Medium", "High"))

#hsb
```


## La variable de interés:  - V. dependiente: MATH (desempeño en matematcas)

  - V. independiente: WRTG
  
- son dos variables de tipo numérico debemos usar una correlación

```{r}
# Gráfica de correlación
library(ggplot2)

base = ggplot(data = hsb, aes(x = WRTG, y = MATH))
base + geom_point(aes(color = SCI))
# Hay aparente relación:
```

#  Índices de correlación:
```{r}
f1 = formula( ~ MATH + WRTG) # Asimétricas, correlacionadas pero ninguna es V.D. o V.I.

# camino parametrico:
pearsonf1 = cor.test(h1, data = hsb)[c('estimate', 'p.value')]
pearsonf1

# camino no parametrico
spearmanf1 = cor.test(f1, data = hsb, method = 'spearman')[c('estimate', 'p.value')]
spearmanf1

# el coeficiente de Pearson 0.6326664 (con p-value= 0). Spearman:0.6415126 (con p-value= 0).
```

```{r}
f2 = formula( ~ MATH + SCI)

# camino parametrico
pearsonf2 = cor.test(f2, data = hsb)[c('estimate', 'p.value')]

# camino no parametrico
spearmanf2 = cor.test(f2, data = hsb, method = 'spearman')[c('estimate', 'p.value')]

# correlación de SCI con MATH, obteniendo el Pearson (0.6495261,p-value= 0) y el Spearman (0.6551515,p-value= 0).
pearsonf2
spearmanf2
```


```{r}
base = ggplot(data = hsb, aes(x = SEX, y = MATH))
base + geom_boxplot(notch = T) +  geom_jitter(color = "black",
                                              size = 0.4,
                                              alpha = 0.9)
```

```{r}
install.packages("ggpubr")
library(ggpubr)
ggerrorplot(data = hsb, x = "SEX", y = "MATH")
```

```{r}
library(ggplot2)
ggplot(hsb, aes(x = MATH)) +
  geom_histogram(aes(y = ..density..), bins = 20, fill = 'green') +
  stat_function(
    fun = dnorm,
    colour = "red",
    args = list(
      mean = mean(hsb$MATH, na.rm = TRUE),
      sd = sd(hsb$MATH, na.rm = TRUE)
    )
  ) +
  facet_grid( ~ SEX) +
  coord_flip()
```

```{r}
# se sugiere normalidad si los puntos no se alejan de la diagonal.

library(ggpubr)
ggqqplot(data = hsb, x = "MATH") + facet_grid(. ~ SEX)
```

```{r}
# install.packages("kableExtra")
library(knitr)
library(magrittr)
library(kableExtra)
h3 = formula(MATH ~ SEX)

# función

shapInfo = function(x) {
  y = shapiro.test(x)
  
  c(y$statistic, y$p.value)
}

tablag = aggregate(data = hsb,
                   h3,
                   FUN = shapInfo)

# para que se vea mejor:

shapiroTable = tablag[, 1] # columna 1
WandPval = as.data.frame(tablag[, 2]) # columnas 2 y 3
shapiroTable = cbind(shapiroTable, WandPval) # todo junto
names(shapiroTable)[c(1, 3)] = c("SEX", "Pval") # cambia nombre de 1 y 2da columna


kable(shapiroTable) %>%
  kable_styling()
```

```{r}
wilcoxh3 = wilcox.test(h3, data = hsb)['p.value']
wilcoxh3
```

```{r}
base = ggplot(data = hsb, aes(x = WRTG, y = MATH))
base + geom_point(aes(color = SEX))
```

```{r}
base + geom_point(aes(size = SCI, color = SEX)) 
```

```{r}
base + geom_point(aes(color = SCI)) + facet_grid( ~ SEX)
```

```{r}
paleta <- c("coral1", "cyan")
colors <- paleta[as.numeric(hsb$SEX)]
scatterplot3d(hsb[, c('SCI', 'WRTG', 'MATH')], color = colors)
```


```{r}
modelo1 = formula(MATH ~ WRTG)
modelo2 = formula(MATH ~ WRTG + SCI)
modelo3 = formula(MATH ~ WRTG + SCI + SEX)
```

```{r}
summary(lm(modelo1, data = hsb))
```

```{r}
#install.packages("stargazer")
library(stargazer)
reg1 = lm(modelo1, data = hsb)
summary(reg1)
stargazer(reg1, type = "text", intercept.bottom = FALSE)
```


```{r}
ggplot(hsb, aes(x = WRTG, y = MATH)) +
  geom_point() +
  geom_smooth(method = lm)
```


```{r}
reg2 = lm(modelo2, data = hsb)
summary(reg2)
stargazer(reg2, type = "text", intercept.bottom = FALSE)
```

```{r}
library(scatterplot3d)
G  <- scatterplot3d(hsb[, c('SCI', 'WRTG', 'MATH')])
G$plane3d(reg2, draw_polygon = TRUE, draw_lines = FALSE)
```

```{r}
tanova = anova(reg1, reg2)
tanova
stargazer(tanova,
          type = 'text',
          summary = F,
          title = "Table de Análisis de Varianza")
```

```{r}
reg3 = lm(modelo3, data = hsb)
summary(reg3)
```

```{r}
library(scatterplot3d)
colors <- paleta[as.numeric(hsb$SEX)]
G  <- scatterplot3d(hsb[, c('SCI', 'WRTG', 'MATH')], color = colors)
G$plane3d(reg2, draw_polygon = TRUE, draw_lines = FALSE)
```

```{r}
library(stargazer)
stargazer(reg1, reg2, reg3, type = "text")
stargazer(reg1,
          reg2,
          reg3,
          type = "text",
          title = "Modelos planteadas",
          digits = 2,
          single.row = F,
          no.space = F,
          intercept.bottom = FALSE,
          dep.var.caption = "Variable dependiente:",
          dep.var.labels = "Desempeño en Matemáticas",
          covariate.labels = c("Constante",
                               "Desempeño en Escritura",
                               "Desempeño en Ciencias",
                               "SEXO (mujer)"),
          keep.stat = c("n", "adj.rsq", "ser"),
          df = F,
          notes.label = "Notas:")
```

```{r}
#install.packages("sjPlot")
library(ggplot2)
library(sjPlot)

plot_models(reg1,
            reg2,
            reg3,
            vline.color = "grey",
            m.labels = c("Modelo 1", "Modelo 2", "Modelo 3"))
```





